version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    container_name: backend
    depends_on:
      - db
    networks:
      - appnet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend
    networks:
      - appnet
    environment:
      - REACT_APP_API_URL=http://backend:5050

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet:
